# Generated by Django 2.2.4 on 2019-10-02 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_birth_date'),
        ('users', '0004_profile_picture'),
    ]

    operations = [
    ]
