# Generated by Django 2.2.4 on 2019-10-02 21:53

from django.db import migrations, models
import naccsweb.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20190826_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduateformmodel',
            name='proof',
            field=models.FileField(storage=naccsweb.storage_backends.PrivateMediaStorage(), upload_to='graduate/proof/'),
        ),
        migrations.AlterField(
            model_name='highschoolformmodel',
            name='proof',
            field=models.FileField(storage=naccsweb.storage_backends.PrivateMediaStorage(), upload_to='highschool/proof/'),
        ),
    ]
