# Generated by Django 2.2.4 on 2019-10-05 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='rank',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
