# Generated by Django 2.2.4 on 2019-10-23 01:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.CharField(blank=True, default=datetime.datetime(2019, 10, 23, 1, 23, 33, 807608), max_length=50),
        ),
    ]
