# Generated by Django 2.2.4 on 2019-10-23 01:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_auto_20191023_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.CharField(blank=True, default=datetime.datetime(2019, 10, 23, 1, 25, 21, 515743), max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='amount_paid',
            field=models.FloatField(default=0),
        ),
    ]
