# Generated by Django 2.2.4 on 2019-10-05 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_player_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
