# Generated by Django 2.2.4 on 2019-10-23 01:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_auto_20191023_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.CharField(blank=True, default=datetime.datetime(2019, 10, 23, 1, 37, 48, 374229), max_length=50),
        ),
    ]
