# Generated by Django 2.2.4 on 2019-10-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_team_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='main_color',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
