# Generated by Django 2.2.4 on 2019-10-23 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_auto_20191023_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.CharField(blank=True, default=0, max_length=50),
        ),
    ]
