# Generated by Django 2.2.4 on 2019-10-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0007_auto_20191005_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='join_password',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
