# Generated by Django 2.2.4 on 2019-10-23 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0007_auto_20191023_0410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='name',
        ),
    ]
