# Generated by Django 2.2.4 on 2019-10-05 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0008_team_join_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='roster',
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='league.Team'),
        ),
    ]
