# Generated by Django 2.2.4 on 2019-10-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0008_auto_20191023_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payerid',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
