# Generated by Django 2.2.4 on 2019-10-08 05:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('league', '0009_auto_20191005_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='league.Team'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('paymentid', models.CharField(blank=True, max_length=25)),
                ('payerid', models.CharField(blank=True, max_length=25)),
                ('date', models.CharField(blank=True, default=datetime.datetime(2019, 10, 8, 5, 22, 10, 805882), max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
