# Generated by Django 2.2.4 on 2019-10-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0009_auto_20191023_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='users',
            field=models.ManyToManyField(to='league.Player'),
        ),
    ]
