# Generated by Django 2.2.4 on 2019-10-08 23:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0010_auto_20191008_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.CharField(blank=True, default=datetime.datetime(2019, 10, 8, 23, 51, 23, 323125), max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentid',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='league.Team'),
        ),
    ]
